### ISSUE TITLE
Steps animation error: ffmpeg not found

### ISSUE THREAD

**Issue by sashaok123** [vladmandic/sd-extension-steps-animation#1]
I have FFMPEG installed in the system PATH, but the extension does not see it.
<img width="481" alt="1" src="https://user-images.githubusercontent.com/27728380/212595122-ce74f1c9-9581-4c6c-9c91-8cbfaeb645c1.png">
<img width="848" alt="2" src="https://user-images.githubusercontent.com/27728380/212595136-32ac4a00-33d2-4207-9447-cbc2fd702ff3.png">
<img width="842" alt="3" src="https://user-images.githubusercontent.com/27728380/212595142-502d5ae4-1835-4445-b4d9-dee216bee7e0.png">

**Comment by vladmandic** [comment]
did you fix this?

**Comment by Gazzoo-byte** [comment]
I had the same issue - the solution for me was to add the ffmpeg location (i.e C:\ffmpeg\bin) to the System Variables Path rather than the User Variables Path, I initially assumed the pip version of ffmpeg would suffice but apparently not

**Comment by Gazzoo-byte** [comment]
Semi related note, it seems that in a situation like this where ffmpeg can't be found, the intermediate folder doesn't get cleaned up - so when ffpmeg gets installed the next animation generated will contain all the previous attempts in addition to the current generation

**Comment by vladmandic** [comment]
@Gazzoo-byte 

extension uses [shutil.which](https://docs.python.org/3/library/shutil.html) to locate `ffmpeg`. if it it really is in your path and not correctly located, its an issue in a core python library itself.

regarding interim files not deleted if `ffmpeg` is not found, i just fixed that.

**Comment by TheProphetGamer** [comment]
I am still getting this error. Can someone show me an example of the path so I can change mine?

**Comment by vladmandic** [comment]
@TheProphetGamer can you post debug output?

**Comment by Gazzoo-byte** [comment]
> I am still getting this error. Can someone show me an example of the path so I can change mine?

@TheProphetGamer https://phoenixnap.com/kb/ffmpeg-windows this was the guide I followed
